export class Certificado{
    constructor(
      public id: number,
      public user_id: any,
      public tiporegistro_id: number,
      public user_post_id: number,
      public cert_asist_avalados_nombre: string,
      public cert_asist_avalados_ano: string,
      public cert_asist_avalados_otrasinst: string,
      public cert_asist_avalados_horas: string,
      public cert_asist_avalados_pdf: string,
      public cert_asist_avalados_status_id: number,
      public cert_asist_no_avalados_nombre: string,
      public cert_asist_no_avalados_ano: string,
      public cert_asist_no_avalados_otrasinst: string,
      public cert_asist_no_avalados_horas: string,
      public cert_asist_no_avalados_pdf: string,
      public cert_asist_no_avalados_status_id: number,
      public cert_o_diploma_academico_nombre: string,
      public cert_o_diploma_academico_cargo: string,
      public cert_o_diploma_academico_tiempo: string,
      public cert_o_diploma_academico_otrasinst: string,
      public cert_o_diploma_academico_pdf: string,
      public cert_o_diploma_academico_status_id: number,
      public cert_o_diploma_asistencial_nombre: string,
      public cert_o_diploma_asistencial_cargo: string,
      public cert_o_diploma_asistencial_tiempo: string,
      public cert_o_diploma_asistencial_otrasinst: string,
      public cert_o_diploma_asistencial_pdf: string,
      public cert_o_diploma_asistencial_status_id: number,
    ){}
  }
